Repository colabhub-dev/colabhub.net, pull requests merged in 2025-06, with the labels that each got.

#1 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#5 ✨ Add Home page component with navigation and hero section
  app/page.tsx
  components/Home.tsx
  components/ui/animated-group.tsx
  components/ui/button.tsx
  next.config.ts
  package-lock.json
  package.json
Labels: enhancement

#9 ✨ Add Footer
  app/layout.tsx
  components/ui/checkbox.tsx
  components/ui/footer-section.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/switch.tsx
  components/ui/textarea.tsx
  components/ui/tooltip.tsx
  package-lock.json
  package.json
Labels: enhancement

#15 📱 Responsive for Footer
  components/ui/footer-section.tsx
Labels: bug

#16 Integretion MongoDB
  .env
  README.md
  lib/mongodb.ts
  package-lock.json
  package.json
Labels: documentation, enhancement

#21 ✨ Add Prettier configuration and scripts for code formatting
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report_ja.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request_ja.md
  .github/workflows/prettier-commit.yml
  README.md
  app/layout.tsx
  app/login/page.tsx
  app/page.tsx
  components.json
  components/Home.tsx
  components/login-form.tsx
  components/ui/animated-group.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/checkbox.tsx
  components/ui/footer-section.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/switch.tsx
  components/ui/textarea.tsx
  components/ui/tooltip.tsx
  docker-compose.devdb.yml
  lib/mongodb.ts
  lib/utils.ts
  next.config.ts
  package-lock.json
  package.json
Labels: enhancement

#33 Migrate to NuxtJs
  .env
  .github/workflows/prettier-check.yml
  .github/workflows/prettier-commit.yml
  .gitignore
  app.vue
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/login/page.tsx
  app/page.tsx
  assets/css/main.css
  components.json
  components/ColorModeButton.vue
  components/CommonHeader.vue
  components/HeaderLoginButton.vue
  components/HeaderMenu.vue
  components/HeaderTitle.vue
  components/Home.tsx
  components/login-form.tsx
  components/theme-provider.tsx
  components/ui/animated-group.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/checkbox.tsx
  components/ui/footer-section.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/switch.tsx
  components/ui/textarea.tsx
  components/ui/tooltip.tsx
  composables/useAuth.ts
  eslint.config.mjs
  index.d.ts
  layouts/default.vue
  lib/mongodb.ts
  lib/utils.ts
  next.config.ts
  nuxt.config.ts
  package-lock.json
  package.json
  pages/index.vue
  pages/login.vue
  postcss.config.mjs
  public/favicon.ico
  public/robots.txt
  server/api/auth/callback/google.get.ts
  server/api/auth/login/google.get.ts
  server/api/auth/me.get.ts
  server/db/mongodb.ts
  server/oauth/google.ts
  server/tsconfig.json
  server/utils/secureCookieOptions.ts
  share/types.ts
  tsconfig.json
Labels: enhancement
